### ISSUE TITLE
Getting data from the Virtual Com Port on windows

### ISSUE THREAD

**Issue by Kortepk** [azonenberg/xptools#26]
Hello, I want to transfer data from the microcontroller in the application. How do I need to configure the data to be read from COM5?

![image](https://github.com/ngscopeclient/scopehal-apps/assets/117624376/51ec0bb6-fcc5-4d5d-863c-163823a3aec5)

**Comment by azonenberg** [comment]
Moved to xptools as that's the root issue.

The UART class in libxptools doesn't currently support Windows serial ports. If you add appropriate code paths to open, set baud rate, and read/write to the COM device object, then the libscopehal SCPIUARTTransport class should pick it up and work fine on Windows.

**Comment by azonenberg** [comment]
As of b91d931b50f1035553f1bacd4491efd0330e4170 we now have Windows UART support, closing.
